CREATE DATABASE IF NOT EXISTS 'uploads' {
    uid VARCHAR(100) NOT NULL,
    model VARCHAR(255) NOT NULL,
    text VARCHAR(1000) ,
    uploaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    upvotes INT NOT NULL DEFAULT 0,
    downvotes INT NOT NULL DEFAULT 0,
    down BOOLEAN NOT NULL DEFAULT FALSE,
};